"""General key class."""
# Copyright 2020-2026 STMicroelectronics
# SPDX-License-Identifier: Apache-2.0


import os
import sys
from cryptography.hazmat.primitives.hashes import Hash, SHA256

AUTOGEN_MESSAGE = "/* Autogenerated by imgtool.py, do not edit. */"


class FileHandler(object):
    def __init__(self, file, *args, **kwargs):
        self.file_in = file
        self.args = args
        self.kwargs = kwargs

    def __enter__(self):
        if isinstance(self.file_in, (str, bytes, os.PathLike)):
            self.file = open(self.file_in, *self.args, **self.kwargs)
        else:
            self.file = self.file_in
        return self.file

    def __exit__(self, *args):
        if self.file != self.file_in:
            self.file.close()


class KeyClass(object):
    def _emit(self, header, trailer, encoded_bytes, indent, file=sys.stdout,
              len_format=None):
        with FileHandler(file, 'w') as file:
            self._emit_to_output(header, trailer, encoded_bytes, indent,
                                     file, len_format)

    def _emit_to_output(self, header, trailer, encoded_bytes, indent, file,
                        len_format=None):
        print(AUTOGEN_MESSAGE, file=file)
        print(header, end='', file=file)
        for count, b in enumerate(encoded_bytes):
            if count % 8 == 0:
                print("\n" + indent, end='', file=file)
            else:
                print(" ", end='', file=file)
            print("0x{:02x},".format(b), end='', file=file)
        print("\n" + trailer, file=file)
        if len_format is not None:
            print(len_format.format(len(encoded_bytes)), file=file)

    def _emit_raw(self, encoded_bytes, file):
        with FileHandler(file, 'wb') as file:
            try:
                # file.buffer is not part of the TextIOBase API
                # and may not exist in some implementations.
                file.buffer.write(encoded_bytes)
            except AttributeError:
                # raw binary data, can be for example io.BytesIO
                file.write(encoded_bytes)

    def emit_c_public(self, file=sys.stdout):
        self._emit(
                header="const unsigned char {}_pub_key{}[] = {{".format(self.shortname(),self.ext()),
                trailer="};",
                encoded_bytes=self.get_public_bytes(),
                indent="    ",
                len_format="const unsigned int {}_pub_key_len{} = {{}};".format(self.shortname(),self.ext()),
                file=file)

    def emit_c_public_hash(self, file=sys.stdout):
        digest = Hash(SHA256())
        digest.update(self.get_public_bytes())
        self._emit(
                header="const unsigned char {}_pub_key{}[] = {{".format(self.shortname(),self.ext()),
                trailer="};",
                encoded_bytes=self.get_public_bytes(),
                indent="    ",
                len_format="const unsigned int {}_pub_key_len{} = {{}};".format(self.shortname(),self.ext()),
                file=file)

    def emit_raw_public(self, file=sys.stdout):
        self._emit_raw(self.get_public_bytes(), file=file)

    def emit_raw_public_hash(self, file=sys.stdout):
        digest = Hash(SHA256())
        digest.update(self.get_public_bytes())
        self._emit_raw(digest.finalize(), file=file)

    def emit_rust_public(self, file=sys.stdout):
        self._emit(
                header="static {}_PUB_KEY: &'static [u8] = &[".format(self.shortname().upper()),
                trailer="];",
                encoded_bytes=self.get_public_bytes(),
                indent="    ",
                file=file)

    def emit_public_pem(self, file=sys.stdout):
        with FileHandler(file, 'w') as file:
            print(str(self.get_public_pem(), 'utf-8'), file=file, end='')

    def emit_private(self, minimal, format,raw, file=sys.stdout):
         if self.shortname()=="sym":
            self._emit(
                header="const unsigned char {}_value[] = {{".format(self.name()),
                trailer="};",
                encoded_bytes=self.get_private_bytes(minimal,format),
                indent="    ",
                len_format="const unsigned int {}_len = {{}};".format(self.name()),
                file=file)

         else:
            value=self.get_private_bytes(minimal,format)
            if "initial_attestation" in self.name() or raw:
               value=value[36:68]
            self._emit(
                header="const unsigned char {}_priv_key[] = {{".format(self.name()),
                trailer="};",
                encoded_bytes=value,
                indent="    ",
                len_format="const unsigned int {}_priv_key_len = {{}};".format(self.name()),
                file=file)

    def emit_private_bin(self, minimal,raw, file=sys.stdout):
        value=self.get_private_bytes(minimal,None)
        if "initial_attestation" in self.name() or raw:
            value=value[36:68]
        sys.stdout.buffer.write(bytes(value))

    def emit_public_bin(self, sha, raw, file=sys.stdout):
        if raw:
        # method available only with ECDSA 256/384 
            value=self.get_public_bytes_raw()
        else:
            value=self.get_public_bytes()
        if sha:
            digest = Hash(SHA256())
            digest.update(value)
            value = digest.finalize()
        sys.stdout.buffer.write(bytes(value))